version: "3.8"

services:
  # Spring Boot Application
  crud-school-app:
    build: .
    ports:
      - "7070:7070"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      - h2-database
    networks:
      - school-network
    restart: unless-stopped

  # H2 Database
  h2-database:
    image: oscarfonts/h2
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - H2_OPTIONS=-ifNotExists
    networks:
      - school-network
    restart: unless-stopped

networks:
  school-network:
    driver: bridge
